name: quantitative-investing-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - requests
  - scipy
  - xlsxwriter
  - jupyter
  - pip
  - pip:
    - yfinance
